app:
  name: 'go-task-management'
  version: '1.0.0'

http:
  port: '8082'

logger:
  log_level: 'debug'
  rollbar_env: 'go-task-management'

trello:
  trello_developer_public_key: ''
  trello_member_token: ''
  trello_username: '''